name: Deploy

on:
  workflow_run:
    workflows: [Test]
    types: [completed]
    branches: ['main']

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: douglasjohnson/vite-react-ts:latest
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      - uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: 'vite-react-ts'
          image: 'douglasjohnson/vite-react-ts'